### PR TITLE
Eventpage widget image title

### PR DESCRIPTION
**Pull request by cluk33**
Add the possibility for the EventPage widget to update a header image and the event title on the page but outside of the target div.

### CODE REVIEW

**Comment by sery0ga** [comment]
@cluk33 I understand the need yet I find the current solution is too specific-oriented for your page markup. What if someone else wants to update other parts of the page? Should they provide more attributes? It will make a final configuration too difficult to work with. 

What I'm thinking about right now is the ability to pass callbacks for different phases. In this case, you'll be to pass a function to 'beforerender' phase, for example. A widget will call it passing an event or a list of events, and you can do whatever you want with it. 

What do you think?

**Comment by cluk33** [comment]
:) For sure a much better solution. I have thought about something similar but my JS skills have limited myself in implementing it. ;)

**Comment by sery0ga** [comment]
@cluk33 it was on my list as well considering other requests from clients. What phases would you like to have? It's good to start with understanding what is needed.

**Comment by cluk33** [comment]
Hm. Usecases I have thought about so far:
* Do something with the data received from the api. Like putting the image or title somewhere. 
* Modify the HTML text generated by the widget before it is rendered.

**Comment by sery0ga** [comment]
@cluk33 okay, got you. Then I'm closing this pull request.

**Pull request closed without merging**
