### PR TITLE
Added future and sortdesc parameter to schedule widget

### PR DESCRIPTION
**Pull request by cluk33**

### CODE REVIEW

**Comment by sery0ga** [comment]
@cluk33 Thanks again for the pull request 👍 

I have no comments on the `future` parameter. As for `sortdesc`, it needs improvements. First, we have an API parameter `sort` which is not in the documentation. It accepts just several values. 

If you want to order events by start date, it should be `sort=+start_date`. The reverse order will be `sort=-start_date`. I suggest using this option instead of sorting in JS. 

I also think the name `sortdesc` is not clear enough. I suggest `sortOrder` with the values `asc` and `desc`.

**Comment by cluk33** [comment]
Thanks, did not know about the API parameter. I will change the code accordingly.

From a user's perspective I would assume that passing 'future: false' would imply rendering the events with descending start time. But that would not match the current behaviour of SidebarEventList widget.

So we could implement that 'future: true' implies sort=+start_date and that 'future: false' implies sort=-start_date. What do you think?

**Comment by sery0ga** [comment]
@cluk33 

> So we could implement that 'future: true' implies sort=+start_date and that 'future: false' implies sort=-start_date. What do you think?

I think it makes total sense. It is done this way in the cabinet.

**Comment by cluk33** [comment]
Close in favour of new approach.

**Pull request closed without merging**
